### PR TITLE
Refactor arduino wrapping system

### PR DESCRIPTION
**Pull request by moiflo033**
Adds nunavut templates to generate the cpp wrappers.

Supersedes #104.

### CODE REVIEW

**Comment by aentinger** [comment]
Very nice :+1: How do you invoke `nnvg` to build the wrapper file(s)?

**Comment by moiflo033** [comment]
There is a Readme included. If that isn't anough i'd be happy to update it.

**Comment by aentinger** [comment]
>There is a Readme included. If that isn't anough i'd be happy to update it.

Terrific. Will try asap! :+1:

**Review by aentinger — CHANGES_REQUESTED** [review]
Good morning @moiflo033 :wave: :coffee: 

I had a first look at your PR and I'm impressed :bow: Nevertheless I've stumbled across a few issues when giving it a try:

* When transpiling `register` data types you'll be needing to prefix the namespace with a `_`, otherwise you have a name-clash with the C keyword `register` which basically means a compilation error.
```diff
/**************************************************************************************
 * NAMESPACE
 **************************************************************************************/

namespace uavcan {
-namespace register {
+namespace register {
```
I recall that this is already somewhat handled by `nunavut`, maybe @pavel-kirienko can advise on a quick remedy for this situation?
* Can you please rename `NSTypes` to `Wrappers`? I'm not terribly happy with `Wrappers` either - so I'm taking alternate suggestions - but `NSTypes`, which I guess stands in for "namespaced types" is not terribly intuitive imho.

**Comment by aentinger** [comment]
Another small wish: If possible, please remove the line-break between Request/Respone, i.e.
```diff
typedef DSDLBaseType<uavcan_register_Access_Request_1_0, uavcan_register_Access_Request_1_0_SERIALIZATION_BUFFER_SIZE_BYTES_, CanardTransferKindMessage> Request_1_0;
-
typedef DSDLBaseType<uavcan_register_Access_Response_1_0, uavcan_register_Access_Response_1_0_SERIALIZATION_BUFFER_SIZE_BYTES_, CanardTransferKindMessage> Response_1_0;
```

**Comment by moiflo033** [comment]
Done. As for the c keywords im not really sure what to do about that.

**Comment by aentinger** [comment]
Superseded by #137.

**Pull request closed without merging**
